baseURL = "/"
languageCode = "en-us"
#title = "PsiCode"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    identifier = "About"
    name = ""  # present to make nav color highlighting sensible when scrolling page
    URL = "/#about"
    weight = 2

    [[menu.nav]]
    name = "News"
    pre = "<i class='far fa-newspaper'></i>"
    URL = "/#portfolio"
    weight = 3

#    [[menu.nav]]
#    name = "Devs"
#    pre = "<i class='fas fa-user'></i>"
#    URL = "#our-team"
#    weight = 7

    #pre = "<i class='fas fa-cat'></i>"
    #URL = "posts/history"
    #URL = "#blog"
    #pre = "<i class='fab fa-twitter'></i>"
    #URL = "https://twitter.com/PSI_Code"

    [[menu.nav]]
    pre = "<i class='fas fa-arrow-alt-circle-down'></i>"
    name = "Downloads"
    URL = "/installs/latest/"
    weight = 8

    [[menu.nav]]
    identifier = "Manual"
    pre = "<i class='fa fa-book'></i>"
    name = "Docs"
    URL = "/psi4manual/master/index.html"
    weight = 4

    [[menu.nav]]
    identifier = "Forum"
    pre = "<i class='fab fa-discourse'></i>"
    name = "Forum"
    URL = "http://forum.psicode.org"
    weight = 5

    [[menu.nav]]
    identifier = "GitHub"
    pre = "<i class='fab fa-github'></i>"
    name = "Code"
    URL = "https://github.com/psi4/psi4/"
    weight = 6

    [[menu.nav]]
    identifier = "Slack"
    pre = "<i class='fab fa-slack'></i>"
    name = "Dev Chat"
    URL = "https://join.slack.com/t/psi4/shared_invite/enQtNDUyOTYzNTE0NjQ3LWExZDhkY2U4MTM1ZDZlNTBkNjMyMDcxZmFkN2NmYmZkMzliNzY2ZDc2OTBlYTk5ZTA2OGRkNWYxNzJmN2QyYWM"
    weight = 8


# Site params
[params]
home = "<i class='fas fa-home'></i>"
logo = "images/psi4square_digit4_overdark_pink.png"
logo_width = 300
favicon = "images/favicon-psi4.ico"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "PsiCode"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "UA-48690006-1"
custom_css = ["css/custom.css", "css/installs-menu.css"]
psi4_html = """<span style="font-family: Optima, sans-serif;font-weight: normal;">P<span style="font-size: 82%;">SI</span>4</span>"""

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/Buckycatcher_JACS_2007_V129_p3843.jpg"
    bgTint = "30, 50, 150, 0.4"
    #heading = "Psi4"
    content= "Open-Source Quantum Chemistry"
    btn = false  # reenable when binder
    btnText="Compute"
    btnURL="#portfolio"
    attribution = true
    btnAttrText = "Image Attribution"
    btnAttrURL = "https://en.wikipedia.org/wiki/Molecular_tweezers#/media/File:Buckycatcher_JACS_2007_V129_p3843.jpg"

    # top announcement
    [params.announce]
    enable = true
    bgImage = "images/backgrounds/light-grey-texture-background_lowres.jpg"
    bgTint = "235, 235, 245, 0.6"
    title = "PsiCon2021"
    titleLText = "Come all in person or online to the"
    titleRText = 'developers conference December 3-4 at the University of Georgia.'
    btnLURL = "https://forms.gle/Wi2mV3KxzJzLQc619"
    btnLText = "Registration"
    btnURL = "posts/psicon-2021"
    btnText = "Schedule"
    btnRURL = ""
    btnRText = "Reports"
    # ======== PsiCon 2020 =========
    # title = "PsiCon2020"
    # titleLText = "Come all virtually to the"
    # titleRText = 'users, developers, and educators conference December 3-5 "at" Georgia Tech.'
    # btnLURL = "https://forms.gle/S63JcyRgM5DpihGE8"
    # btnLText = "Registration"
    # btnURL = "posts/psicon-2020"
    # ======== PsiCon 2019 =========
    # title = "PsiCon2019"
    # titleLText = "Come all to the"
    # titleRText = "users, developers, and educators conference November 16–17 at Emory."
    # btnLURL = "https://forms.gle/QHse8mzZptCwFDGj9"
    # btnLText = "Registration"
    # btnURL = "posts/psicon-2019"

    # call to action
    [params.cta]
    enable = true
    bgImage = "images/backgrounds/light-grey-texture-background_lowres.jpg"
    bgTint = "235, 235, 245, 0.6"
    title = "Get Started with Psi4"
    #content = ""
    btnURL = "http://psicode.org/psi4manual/master/index_tutorials.html"
    btnText = "Tutorials"
    btnLURL = "installs/latest"
    btnLText = "Downloads"
    btnRURL = ""
    btnRText = "Programming"
    btnRRURL = "posts/psi4education"
    btnRRText = "Psi4Education"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/blue-brush-paint-texture_lowres.jpg"
    bgTint = "200, 200, 220, 0.35"

        [[params.counter.counterItem]]
        title = "Ecosystem Projects"
        icon = "fas fa-project-diagram"
        count = "20"  # hardcoding for now
        URL = '#'

        [[params.counter.counterItem]]
        title = "Psi4NumPy Tutorials"
        icon = "fas fa-calculator"
        count = "73"  # edit here
        URL = "https://github.com/psi4/psi4numpy"

        [[params.counter.counterItem]]
        title = "Psi4Education Labs"
        icon = "fas fa-chalkboard-teacher"
        count = "13"  # edit here
        URL = "posts/psi4education"

        [[params.counter.counterItem]]
        title = "Citing Papers"
        icon = "fas fa-file-code"
        count = "0"
        URL = "https://scholar.google.com/scholar?cites=4895426460461757249&hl=en&scipsc=&q=&scisbd=1"

        [[params.counter.counterItem]]
        title = "Positive Feedback"
        icon = "fas fa-beer"
        count = "0"  # GH API
        URL = "https://github.com/psi4/psi4/stargazers"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "fas fa-mug-hot"
        count = "0"  # GH API
        URL = "https://github.com/psi4/psi4/commits/master"

        [[params.counter.counterItem]]
        title = "Days Since Last Release"
        icon = "fas fa-cube"
        count = "0"  # GH API
        URL = "categories/releases"

        [[params.counter.counterItem]]
        title = "Contributors"
        icon = "fas fa-user"
        count = "0"  # GH API
        URL = "posts/ghauthors"

    # footer
    [params.footer]
        copyright = "Psi4 Project and Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "fas fa-home"
        url = "http://psicode.org/"

        [[params.footer.socialIcon]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/PSI_Code"

        [[params.footer.socialIcon]]
        icon = "fa fa-book"
        url = "http://psicode.org/psi4manual/master/index.html"

        [[params.footer.socialIcon]]
        icon = "fab fa-discourse"
        url = "http://forum.psicode.org"

        [[params.footer.socialIcon]]
        icon = "fab fa-github"
        url = "https://github.com/psi4/psi4/"

        [[params.footer.socialIcon]]
        icon = "fab fa-slack"
        url = "https://join.slack.com/t/psi4/shared_invite/enQtNDUyOTYzNTE0NjQ3LWExZDhkY2U4MTM1ZDZlNTBkNjMyMDcxZmFkN2NmYmZkMzliNzY2ZDc2OTBlYTk5ZTA2OGRkNWYxNzJmN2QyYWM"

#[sitemap]
#  changefreq = "monthly"
#  filename = "sitemap.xml"
#  priority = 0.5
