[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/psi4manual/master/*"
  #to = "https://psi4manual.netlify.app/:splat"
  to = "https://psi4.github.io/psi4docs/master/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/psi4manual/1.10.x/*"
  to = "https://psi4.github.io/psi4docs/1.10.x/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/psi4manual/1.9.x/*"
  to = "https://psi4.github.io/psi4docs/1.9.x/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/psi4manual/1.8.x/*"
  to = "https://psi4.github.io/psi4docs/1.8.x/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/psi4manual/1.7.x/*"
  to = "https://psi4.github.io/psi4docs/1.7.x/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/psi4manual/1.6.x/*"
  to = "https://psi4.github.io/psi4docs/1.6.x/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/downloads*"
  to = "/installs/latest"
  status = 301
